const recruits = [
  {number:'75',name:'Kyle Skrepnek',position:'Offensive Line',year:'2030',image:'f75-8821a6a2.jpg'},
  {number:'18',name:'Tyson Castillo',position:'Wide Receiver',year:'2028',image:'f18-3c46f50a.jpg'},
  {number:'49',name:'Jack Hayes',position:'Linebacker',year:'2028',image:'f49-8e881ab6.jpg'},
  {number:'51',name:'Reed Weiny',position:'Offensive Line',year:'2028',image:'f51-30e2bd94.jpg'},
  {number:'85',name:'Carson Stoddard',position:'Tight End',year:'2027',image:'f85-34ada187.jpg'},
  {number:'72',name:'Jemil Jackson',position:'Defensive Line',year:'2029',image:'f72-0599625c.jpg'},
];

export default function Recruiting() {
  return <main className="recruiting-page"><header className="subpage-header"><a href="/">← Back to Edmond North Football</a><img src="/assets/wordmark.png" alt="Edmond North Football" /></header><section className="recruiting recruiting-standalone"><div className="recruiting-watermark" aria-hidden="true">North</div><div className="recruiting-intro"><div><p className="eyebrow blue">Recruiting center</p><h1>Built here.<br/>Ready for next.</h1><p>Meet the student-athletes representing Edmond North. Open a card for profile details, highlight access, and direct recruiting contact with the program.</p></div><a className="button dark" href="mailto:huskies@edmondnorthfb.com?subject=Edmond%20North%20Football%20Recruiting">Contact the program →</a></div><div className="recruiting-grid">{recruits.map(player=><details className="player-profile" key={player.number}><summary><div className="player-photo"><img src={`/assets/players/${player.image}`} alt={`${player.name}, Edmond North football ${player.position}`}/><span className="player-number">{player.number}</span><span className="profile-prompt">View profile <b aria-hidden="true">+</b></span></div><div className="player-info"><div><p className="player-position">{player.position}</p><h2>{player.name}</h2><span>Class of {player.year} · Edmond North</span></div></div></summary><div className="profile-detail"><div className="profile-measurables"><span><small>Class</small><b>{player.year}</b></span><span><small>Position</small><b>{player.position}</b></span><span><small>Program</small><b>6A-I</b></span></div><p>Verified measurements, academics, honors, and season statistics will be added by the Edmond North coaching staff.</p><div className="profile-actions"><a href="https://www.hudl.com" target="_blank" rel="noreferrer">Watch highlights <span aria-hidden="true">▶</span></a><a href={`mailto:huskies@edmondnorthfb.com?subject=${encodeURIComponent(`Recruiting inquiry: ${player.name} #${player.number}`)}`}>Contact coaches <span aria-hidden="true">→</span></a></div></div></details>)}</div></section></main>;
}
