const games = [
  { date: 'AUG 20', opponent: 'Yukon', detail: 'Scrimmage · 6:00 PM', place: 'Home', logo: 'yukon-2a179732.png' },
  { date: 'AUG 28', opponent: 'Edmond Santa Fe', detail: 'Season opener · 7:00 PM', place: 'Home', logo: 'edmond-santa-fe-6c4a73a2.png' },
  { date: 'SEP 04', opponent: 'Deer Creek', detail: 'Friday · 7:00 PM', place: 'Away', logo: 'deer-creek-d9a03f17.png' },
  { date: 'SEP 11', opponent: 'Putnam City North', detail: 'Friday · 7:00 PM', place: 'Away', logo: 'putnam-city-north-c27f1bef.png' },
  { date: 'SEP 25', opponent: 'Edmond Memorial', detail: 'Friday · 7:00 PM', place: 'Away', logo: 'edmond-memorial-45f59d00.png', ticket: 'https://gofan.co/event/6743866?schoolId=OK21048' },
  { date: 'OCT 02', opponent: 'Norman North', detail: 'Homecoming · 7:00 PM', place: 'Home', logo: 'norman-north-b7d4bc4b.png', ticket: 'https://gofan.co/event/6739397?schoolId=OK21048' },
  { date: 'OCT 09', opponent: 'Mustang', detail: 'Friday · 7:00 PM', place: 'Away', logo: 'mustang-6cf56a6f.png', ticket: 'https://gofan.co/event/6723321?schoolId=OK21048' },
  { date: 'OCT 15', opponent: 'Westmoore', detail: 'Thursday · 7:00 PM', place: 'Home', logo: 'westmoore-edf593ef.png' },
  { date: 'OCT 23', opponent: 'Bixby', detail: 'Friday · 7:00 PM', place: 'Home', logo: 'bixby-06708da4.png', ticket: 'https://gofan.co/event/6739395?schoolId=OK21048' },
  { date: 'OCT 30', opponent: 'Southmoore', detail: 'Friday · 7:00 PM', place: 'Away', logo: 'southmoore-823ad3d7.png' },
  { date: 'NOV 05', opponent: 'Broken Arrow', detail: 'Senior Night · 7:00 PM', place: 'Home', logo: 'broken-arrow-84cc9e55.png', ticket: 'https://gofan.co/event/6739394?schoolId=OK21048' },
];

const coaches = [['Carter Whitson','Head Coach'],['Joel Blumenthal','Offensive Coordinator / Quarterbacks'],['Tyler Caid','Defensive Coordinator / Linebackers'],['Will Taylor','Co-Defensive Coordinator / OLB']];
const recruits = [
  ['75','Kyle Skrepnek','Offensive Line','2030','f75-8821a6a2.jpg'],
  ['18','Tyson Castillo','Wide Receiver','2028','f18-3c46f50a.jpg'],
  ['49','Jack Hayes','Linebacker','2028','f49-8e881ab6.jpg'],
  ['51','Reed Weiny','Offensive Line','2028','f51-30e2bd94.jpg'],
  ['85','Carson Stoddard','Tight End','2027','f85-34ada187.jpg'],
  ['72','Jemil Jackson','Defensive Line','2029','f72-0599625c.jpg'],
];

export default function Home() {
  return <main>
    <div className="topbar"><span>Home of the Huskies</span><div><a href="#contact">Parent hub</a><a href="/recruiting/">Recruiting</a><a href="#contact">Contact</a></div></div>
    <header className="site-header"><a className="brand" href="#top" aria-label="Edmond North Football home"><img src="/assets/wordmark.png" alt="Edmond North Football" /></a><nav aria-label="Main navigation"><a href="/schedule/">Schedule</a><a href="#team">Team</a><a href="#support">Sled Team</a><a href="#media">Media</a></nav><a className="header-cta" href="/menu/"><span aria-hidden="true">☰</span> Menu</a></header>

    <section id="top" className="hero"><video className="hero-photo" autoPlay muted loop playsInline poster="/assets/hero.jpg" aria-label="Edmond North Huskies football highlight video"><source src="/assets/hero-video.mov?v=720" type="video/quicktime"/></video><div className="hero-shade"/><div className="hero-copy"><h1>We Are<br/><em>the North.</em></h1><p className="eyebrow hero-location">Edmond, Oklahoma · Class 6A-I</p><div className="hero-actions"><a className="button light" href="/schedule/">2026 schedule <span aria-hidden="true">→</span></a><a className="text-link" href="#support">Join the Sled Team</a></div></div><div className="hero-stat"><span>2026</span><small>Varsity season</small></div></section>

    <section id="schedule" className="schedule-strip"><div className="section-lead"><div><p className="eyebrow blue">Next up · September 19</p><h2>Friday nights start here.</h2></div><a href="/schedule/">Full schedule <span aria-hidden="true">→</span></a></div><div className="game-row">{games.slice(4,5).map((game,index)=><article className={index===0?'game featured':'game'} key={game.opponent}><div className="game-date">{game.date}</div><img src={`/assets/opponents/${game.logo}`} alt=""/><div><p>{game.opponent}</p><span>{game.detail}</span></div><div className="game-place"><span aria-hidden="true">◆</span>{game.place}</div>{game.ticket&&<a className="upcoming-ticket" href={game.ticket} target="_blank" rel="noreferrer" aria-label={`Buy tickets for ${game.opponent}`}>🎟 Tickets</a>}</article>)}</div></section>


    <section id="media" className="media-feature"><img src="/assets/game-night.jpg" alt="Edmond North offense during a night game"/><div className="media-overlay"/><div className="media-copy"><p className="eyebrow">Game day</p><h2>Can&apos;t make the stands?</h2><p>Follow every Friday night with live KREF coverage and program updates from the sideline.</p><div><a className="button light" href="https://krefsports.tv/edmond-north/" target="_blank" rel="noreferrer"><span aria-hidden="true">●</span> Watch every game</a><a className="button outline" href="https://www.instagram.com/edmondnorthfb/" target="_blank" rel="noreferrer"><span aria-hidden="true">◎</span> Follow the Huskies</a></div></div></section>

    <section id="coaches" className="coaches"><div className="section-lead"><div><p className="eyebrow blue">Leadership</p><h2>Meet the staff.</h2></div><a href="mailto:huskies@edmondnorthfb.com?subject=Coaching%20Staff">Contact the program <span aria-hidden="true">→</span></a></div><div className="coach-grid">{coaches.map(([name,role],i)=><article key={name}><span>0{i+1}</span><div><h3>{name}</h3><p>{role}</p></div></article>)}</div></section>

    <section id="support" className="support"><div className="support-copy"><p className="eyebrow">Back the pack</p><h2>Put your name<br/>behind the North.</h2><p>Sled Team membership and local sponsorships directly support every level of Edmond North Football—from equipment and meals to camps and team experiences.</p><div><a className="button light" href="https://pci.jotform.com/form/260876506724161" target="_blank" rel="noreferrer">Join the Sled Team <span aria-hidden="true">→</span></a><a className="button outline" href="https://pci.jotform.com/form/260876506724161" target="_blank" rel="noreferrer">Become a sponsor</a></div></div><div className="support-mark"><img src="/assets/badge.png" alt="Edmond North Huskies badge"/><span>Every player.<br/>Every level.<br/>One program.</span></div></section>

    <section id="tradition" className="tradition"><p className="eyebrow blue">The standard</p><blockquote>“Building champions on and off the field.”</blockquote><div className="program-levels"><article><strong>Varsity</strong><small>Friday nights</small><a href="/schedule/#varsity">Full varsity schedule <span aria-hidden="true">→</span></a></article><article><strong>JV</strong><small>Next men up</small><div className="compact-next-game"><time dateTime="2026-09-28"><b>SEP</b> 28</time><span><b>Next game · Home</b>Edmond Memorial · 7:00 PM</span></div><a href="/schedule/#jv">Full JV schedule <span aria-hidden="true">→</span></a></article><article><strong>9th Grade</strong><small>The foundation</small><div className="compact-next-game"><time dateTime="2026-09-21"><b>SEP</b> 21</time><span><b>Next game · Home</b>Moore · 5:30 PM</span></div><a href="/schedule/#freshman">Full 9th grade schedule <span aria-hidden="true">→</span></a></article></div></section>

    <section id="sponsors" className="sponsors"><div className="sponsors-copy"><h2>Thank you to our<br/>sponsors!</h2><p>We are incredibly grateful to our sponsors for their continued support of Edmond North Football. Your generosity fuels our programs, empowers our student-athletes, and helps us create unforgettable experiences—from youth camps to Friday night lights.</p></div><div className="sponsor-rail" aria-label="Edmond North Football sponsors"><div className="sponsor-track"><div className="sponsor-name citizens">Citizens Bank<br/><small>of Edmond · Since 1901</small></div><div className="sponsor-name club">Club<br/><small>Car Wash</small></div><div className="sponsor-name firehouse">Firehouse<br/><small>Subs</small></div><div className="sponsor-name habit">Habit</div><div className="sponsor-name edmond-first">Edmond First<br/><small>United Methodist Church</small></div><div className="sponsor-name citizens" aria-hidden="true">Citizens Bank<br/><small>of Edmond · Since 1901</small></div><div className="sponsor-name club" aria-hidden="true">Club<br/><small>Car Wash</small></div><div className="sponsor-name firehouse" aria-hidden="true">Firehouse<br/><small>Subs</small></div><div className="sponsor-name habit" aria-hidden="true">Habit</div><div className="sponsor-name edmond-first" aria-hidden="true">Edmond First<br/><small>United Methodist Church</small></div></div></div><a className="sponsor-button" href="https://pci.jotform.com/form/260876506724161" target="_blank" rel="noreferrer">Become a Sponsor</a></section>

    <footer id="contact"><div className="footer-brand"><img src="/assets/wordmark.png" alt="Edmond North Football"/><p>1001 W. Danforth Rd<br/>Edmond, OK 73003</p></div><div><h3>Program</h3><a href="#schedule">Schedule</a><a href="#team">Team</a><a href="#coaches">Coaches</a><a href="#recruiting">Recruiting</a></div><div><h3>Get involved</h3><a href="#support">Sled Team</a><a href="#support">Sponsors</a><a href="#media">Media</a><a href="mailto:huskies@edmondnorthfb.com">Contact</a></div><div className="footer-contact"><h3>Stay connected</h3><a href="mailto:huskies@edmondnorthfb.com">huskies@edmondnorthfb.com</a><a href="tel:4053402875">(405) 340-2875</a><a href="https://www.instagram.com/edmondnorthfb/" target="_blank" rel="noreferrer">Instagram</a></div><p className="copyright">© 2026 Edmond North Football · Home of the Huskies</p></footer>
  </main>;
}
