const games = [
  { date: 'AUG 20', opponent: 'Yukon', detail: 'Scrimmage · 6:00 PM', place: 'Home', logo: 'yukon-2a179732.png' },
  { date: 'AUG 28', opponent: 'Edmond Santa Fe', detail: 'Season opener · 7:00 PM', place: 'Home', logo: 'edmond-santa-fe-6c4a73a2.png' },
  { date: 'SEP 04', opponent: 'Deer Creek', detail: 'Friday · 7:00 PM', place: 'Away', logo: 'deer-creek-d9a03f17.png' },
  { date: 'SEP 11', opponent: 'Putnam City North', detail: 'Friday · 7:00 PM', place: 'Away', logo: 'putnam-city-north-c27f1bef.png' },
  { date: 'SEP 25', opponent: 'Edmond Memorial', detail: 'Friday · 7:00 PM', place: 'Away', logo: 'edmond-memorial-45f59d00.png', ticket: 'https://gofan.co/event/6743866?schoolId=OK21048' },
  { date: 'OCT 02', opponent: 'Norman North', detail: 'Homecoming · 7:00 PM', place: 'Home', logo: 'norman-north-b7d4bc4b.png', ticket: 'https://gofan.co/event/6739397?schoolId=OK21048' },
  { date: 'OCT 09', opponent: 'Mustang', detail: 'Friday · 7:00 PM', place: 'Away', logo: 'mustang-6cf56a6f.png', ticket: 'https://gofan.co/event/6723321?schoolId=OK21048' },
  { date: 'OCT 15', opponent: 'Westmoore', detail: 'Thursday · 7:00 PM', place: 'Home', logo: 'westmoore-edf593ef.png' },
  { date: 'OCT 23', opponent: 'Bixby', detail: 'Friday · 7:00 PM', place: 'Home', logo: 'bixby-06708da4.png', ticket: 'https://gofan.co/event/6739395?schoolId=OK21048' },
  { date: 'OCT 30', opponent: 'Southmoore', detail: 'Friday · 7:00 PM', place: 'Away', logo: 'southmoore-823ad3d7.png' },
  { date: 'NOV 05', opponent: 'Broken Arrow', detail: 'Senior Night · 7:00 PM', place: 'Home', logo: 'broken-arrow-84cc9e55.png', ticket: 'https://gofan.co/event/6739394?schoolId=OK21048' },
];

const recruits = [
  ['75','Kyle Skrepnek','Offensive Line','2030','f75-8821a6a2.jpg'],
  ['18','Tyson Castillo','Wide Receiver','2028','f18-3c46f50a.jpg'],
  ['49','Jack Hayes','Linebacker','2028','f49-8e881ab6.jpg'],
  ['51','Reed Weiny','Offensive Line','2028','f51-30e2bd94.jpg'],
  ['85','Carson Stoddard','Tight End','2027','f85-34ada187.jpg'],
  ['72','Jemil Jackson','Defensive Line','2029','f72-0599625c.jpg'],
];

function SocialIcon({name}:{name:'instagram'|'facebook'|'x'}) {
  if (name === 'facebook') return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M24 12.07C24 5.45 18.63.07 12 .07S0 5.45 0 12.07c0 5.99 4.39 10.96 10.13 11.85v-8.44H7.08v-3.42h3.05V9.47c0-3.01 1.79-4.67 4.53-4.67 1.31 0 2.69.24 2.69.24v2.95h-1.51c-1.49 0-1.96.93-1.96 1.87v2.25h3.33l-.53 3.42h-2.8v8.44C19.61 23.03 24 18.06 24 12.07Z"/></svg>;
  if (name === 'x') return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M18.24 2.25h3.31l-7.23 8.26 8.51 11.24h-6.66l-5.21-6.82-5.97 6.82H1.68l7.73-8.84L1.25 2.25h6.83l4.71 6.23 5.45-6.23Zm-1.16 17.52h1.83L7.08 4.13H5.12l11.96 15.64Z"/></svg>;
  return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4.2"/><circle cx="17.5" cy="6.7" r="1.1"/></svg>;
}

export default function Home() {
  return <main>
    <div className="topbar"><span>Home of the Huskies</span><div><a href="/program/">Game day program</a><a href="/recruiting/">Recruiting</a><a href="#contact">Contact</a></div></div>
    <header className="site-header"><a className="brand" href="#top" aria-label="Edmond North Football home"><img src="/assets/wordmark.png" alt="Edmond North Football" /></a><nav aria-label="Main navigation"><a href="/schedule/">Schedule</a><a href="/huskies-football/">The Huskies</a><a href="#support">Sled Team</a><a href="#media">Media</a></nav><a className="header-cta" href="/menu/"><span aria-hidden="true">☰</span> Menu</a></header>

    <section id="top" className="hero"><video className="hero-photo" autoPlay muted loop playsInline poster="/assets/hero.jpg" aria-label="Edmond North Huskies football highlight video"><source src="/assets/hero-video.mov?v=720" type="video/quicktime"/></video><div className="hero-shade"/><div className="hero-copy"><h1>We Are<br/><em>the North.</em></h1><p className="eyebrow hero-location">Edmond, Oklahoma · Class 6A-I</p><div className="hero-actions"><a className="button light" href="/schedule/">2026 schedule <span aria-hidden="true">→</span></a><a className="text-link" href="#support">Join the Sled Team</a></div></div><div className="hero-stat"><span>2026</span><small>Varsity season</small></div></section>

    <section id="schedule" className="schedule-strip"><div className="section-lead"><div><p className="eyebrow blue">Next up · September 25</p><h2>Friday nights start here.</h2></div><a href="/schedule/">Full schedule <span aria-hidden="true">→</span></a></div><div className="kickoff-countdown" data-kickoff="2026-09-25T19:00:00-05:00" aria-label="Countdown to kickoff"><p>Kickoff in</p><div><span><b data-unit="days">00</b><small>Days</small></span><span><b data-unit="hours">00</b><small>Hours</small></span><span><b data-unit="minutes">00</b><small>Minutes</small></span><span><b data-unit="seconds">00</b><small>Seconds</small></span></div></div><div className="game-row">{games.slice(4,5).map((game,index)=><article className={index===0?'game featured':'game'} key={game.opponent}><div className="game-date">{game.date}</div><img src={`/assets/opponents/${game.logo}`} alt=""/><div><p>{game.opponent}</p><span>{game.detail}</span></div>{game.ticket&&<div className="game-actions"><a className="upcoming-ticket" href={game.ticket} target="_blank" rel="noreferrer" aria-label={`Buy tickets for ${game.opponent}`}>🎟 Tickets</a><div className="game-subactions"><a className="upcoming-preview" href="/program/">Game preview →</a><div className="game-place"><span aria-hidden="true">◆</span>{game.place}</div></div></div>}</article>)}</div></section>


    <section id="media" className="media-feature"><img src="/assets/game-night.jpg" alt="Edmond North offense during a night game"/><div className="media-overlay"/><div className="media-copy"><p className="eyebrow">Game day</p><h2>Can&apos;t make the stands?</h2><p>Follow every Friday night with live KREF coverage and program updates from the sideline.</p><div><a className="button light" href="https://krefsports.tv/edmond-north/" target="_blank" rel="noreferrer"><span aria-hidden="true">●</span> Watch every game</a><a className="button outline" href="https://www.instagram.com/edmondnorthfb/" target="_blank" rel="noreferrer"><span aria-hidden="true">◎</span> Follow the Huskies</a></div></div></section>

    <section id="tradition" className="tradition"><p className="eyebrow blue">The standard</p><blockquote>“Building champions on and off the field.”</blockquote><div className="program-levels"><article><strong>JV</strong><small>Next men up</small><div className="compact-next-game"><time dateTime="2026-09-28"><b>SEP</b> 28</time><span><b>Next game · Home</b>Edmond Memorial · 7:00 PM</span></div><a href="/schedule/#jv">Full JV schedule <span aria-hidden="true">→</span></a></article><article><strong>9th Grade</strong><small>The foundation</small><div className="compact-next-game"><time dateTime="2026-09-21"><b>SEP</b> 21</time><span><b>Next game · Home</b>Moore · 5:30 PM</span></div><a href="/schedule/#freshman">Full 9th grade schedule <span aria-hidden="true">→</span></a></article></div></section>

    <section id="support" className="support"><div className="support-copy"><p className="eyebrow">Back the pack</p><h2>Put your name<br/>behind the Huskies.</h2><p>Join the Sled Team, the Edmond North Football Booster Club. Membership directly supports every level of the program—from equipment and meals to camps and team experiences.</p><div><a className="button light" href="https://pci.jotform.com/form/260876506724161" target="_blank" rel="noreferrer">Join the Sled Team <span aria-hidden="true">→</span></a><a className="button outline" href="/donate/">Donate <span aria-hidden="true">→</span></a></div></div><div className="support-mark"><img src="/assets/badge.png" alt="Edmond North Huskies badge"/><span>Every player.<br/>Every level.<br/>One program.</span></div></section>

    <section id="sponsors" className="sponsors"><div className="sponsors-copy"><h2>Thank you to our<br/>sponsors!</h2><p>We are incredibly grateful to our sponsors for their continued support of Edmond North Football. Your generosity fuels our programs, empowers our student-athletes, and helps us create unforgettable experiences—from youth camps to Friday night lights.</p></div><div className="sponsor-rail" aria-label="Edmond North Football sponsors"><div className="sponsor-track"><div className="sponsor-name citizens">Citizens Bank<br/><small>of Edmond · Since 1901</small></div><div className="sponsor-name club">Club<br/><small>Car Wash</small></div><div className="sponsor-name firehouse">Firehouse<br/><small>Subs</small></div><div className="sponsor-name habit">Habit</div><div className="sponsor-name edmond-first">Edmond First<br/><small>United Methodist Church</small></div><div className="sponsor-name citizens" aria-hidden="true">Citizens Bank<br/><small>of Edmond · Since 1901</small></div><div className="sponsor-name club" aria-hidden="true">Club<br/><small>Car Wash</small></div><div className="sponsor-name firehouse" aria-hidden="true">Firehouse<br/><small>Subs</small></div><div className="sponsor-name habit" aria-hidden="true">Habit</div><div className="sponsor-name edmond-first" aria-hidden="true">Edmond First<br/><small>United Methodist Church</small></div></div></div><a className="sponsor-button" href="https://pci.jotform.com/form/260876506724161" target="_blank" rel="noreferrer">Become a Sponsor</a></section>

    <script dangerouslySetInnerHTML={{__html:`(()=>{const el=document.querySelector('.support-mark');if(el&&!matchMedia('(prefers-reduced-motion: reduce)').matches){let queued=false;const move=()=>{const r=el.getBoundingClientRect();const raw=(innerHeight/2-(r.top+r.height/2))*.16;el.style.setProperty('--parallax-y',Math.max(-65,Math.min(65,raw))+'px');queued=false};addEventListener('scroll',()=>{if(!queued){requestAnimationFrame(move);queued=true}},{passive:true});move()}const clock=document.querySelector('.kickoff-countdown');if(clock){const target=new Date(clock.dataset.kickoff).getTime();const tick=()=>{const left=Math.max(0,target-Date.now());const values={days:Math.floor(left/86400000),hours:Math.floor(left/3600000)%24,minutes:Math.floor(left/60000)%60,seconds:Math.floor(left/1000)%60};Object.entries(values).forEach(([unit,value])=>{const node=clock.querySelector('[data-unit="'+unit+'"]');if(node)node.textContent=String(value).padStart(2,'0')});if(!left)clock.classList.add('kickoff-live')};tick();setInterval(tick,1000)}})()`}} />
    <footer id="contact"><div className="footer-brand"><img src="/assets/wordmark.png" alt="Edmond North Football"/><p>1001 W. Danforth Rd<br/>Edmond, OK 73003</p></div><div><h3>Program</h3><a href="#schedule">Schedule</a><a href="/roster/">Roster</a><a href="#tradition">Program</a></div><div><h3>Get involved</h3><a href="#support">Sled Team</a><a href="#sponsors">Sponsors</a><a href="#media">Media</a><a href="mailto:huskies@edmondnorthfb.com">Contact</a></div><div className="footer-contact"><h3>Stay connected</h3><a href="mailto:huskies@edmondnorthfb.com">huskies@edmondnorthfb.com</a><a href="tel:4053402875">(405) 340-2875</a><div className="footer-social" aria-label="Edmond North Football social media"><a href="https://www.instagram.com/edmondnorthfb/" target="_blank" rel="noreferrer" aria-label="Edmond North Football on Instagram"><SocialIcon name="instagram"/></a><a href="https://www.facebook.com/p/Edmond-North-Football-100064023400992/" target="_blank" rel="noreferrer" aria-label="Edmond North Football on Facebook"><SocialIcon name="facebook"/></a><a href="https://x.com/edmondnorthfb?s=11" target="_blank" rel="noreferrer" aria-label="Edmond North Football on X"><SocialIcon name="x"/></a></div></div><p className="copyright">© 2026 Edmond North Football · Home of the Huskies</p></footer>
  </main>;
}
