const games = [
  { date: 'AUG 20', opponent: 'Yukon', detail: 'Scrimmage · 6:00 PM', place: 'Home', logo: 'yukon-2a179732.png' },
  { date: 'AUG 28', opponent: 'Edmond Santa Fe', detail: 'Season opener · 7:00 PM', place: 'Home', logo: 'edmond-santa-fe-6c4a73a2.png' },
  { date: 'SEP 04', opponent: 'Deer Creek', detail: 'Friday · 7:00 PM', place: 'Away', logo: 'deer-creek-d9a03f17.png' },
  { date: 'SEP 11', opponent: 'Putnam City North', detail: 'Friday · 7:00 PM', place: 'Away', logo: 'putnam-city-north-c27f1bef.png' },
  { date: 'SEP 25', opponent: 'Edmond Memorial', detail: 'Friday · 7:00 PM', place: 'Away', logo: 'edmond-memorial-45f59d00.png' },
  { date: 'OCT 02', opponent: 'Norman North', detail: 'Homecoming · 7:00 PM', place: 'Home', logo: 'norman-north-b7d4bc4b.png' },
  { date: 'OCT 09', opponent: 'Mustang', detail: 'Friday · 7:00 PM', place: 'Away', logo: 'mustang-6cf56a6f.png' },
  { date: 'OCT 15', opponent: 'Westmoore', detail: 'Thursday · 7:00 PM', place: 'Home', logo: 'westmoore-edf593ef.png' },
  { date: 'OCT 23', opponent: 'Bixby', detail: 'Friday · 7:00 PM', place: 'Home', logo: 'bixby-06708da4.png' },
  { date: 'OCT 30', opponent: 'Southmoore', detail: 'Friday · 7:00 PM', place: 'Away', logo: 'southmoore-823ad3d7.png' },
  { date: 'NOV 05', opponent: 'Broken Arrow', detail: 'Senior Night · 7:00 PM', place: 'Home', logo: 'broken-arrow-84cc9e55.png' },
];

const coaches = [['Carter Whitson','Head Coach'],['Joel Blumenthal','Offensive Coordinator / Quarterbacks'],['Tyler Caid','Defensive Coordinator / Linebackers'],['Will Taylor','Co-Defensive Coordinator / OLB']];
const recruits = [
  ['75','Player 75','Offensive Line','2026','f75-8821a6a2.jpg'],
  ['18','Player 18','Wide Receiver','2026','f18-3c46f50a.jpg'],
  ['49','Player 49','Linebacker','2027','f49-8e881ab6.jpg'],
  ['51','Player 51','Offensive Line','2027','f51-30e2bd94.jpg'],
  ['85','Player 85','Tight End','2027','f85-34ada187.jpg'],
  ['72','Player 72','Defensive Line','2028','f72-0599625c.jpg'],
];

export default function Home() {
  return <main>
    <div className="topbar"><span>Home of the Huskies</span><div><a href="#parents">Parent hub</a><a href="/recruiting/">Recruiting</a><a href="#contact">Contact</a></div></div>
    <header className="site-header"><a className="brand" href="#top" aria-label="Edmond North Football home"><img src="/assets/wordmark.png" alt="Edmond North Football" /></a><nav aria-label="Main navigation"><a href="#schedule">Schedule</a><a href="#program">Program</a><a href="#team">Team</a><a href="#support">Sled Team</a><a href="#media">Media</a></nav><a className="header-cta" href="https://www.goenhsathletics.com/KREF-Streaming" target="_blank" rel="noreferrer"><span aria-hidden="true">●</span> Listen live</a></header>

    <section id="top" className="hero"><img className="hero-photo" src="/assets/hero.jpg" alt="Edmond North Huskies football team taking the field"/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">Edmond, Oklahoma · Class 6A-I</p><h1>Built in the<br/><em>North.</em></h1><p className="hero-deck">The official home of Edmond North Football. One program, one standard, one pack.</p><div className="hero-actions"><a className="button light" href="#schedule">2026 schedule <span aria-hidden="true">→</span></a><a className="text-link" href="#support">Join the Sled Team</a></div></div><div className="hero-stat"><span>2026</span><small>Varsity season</small></div></section>

    <section id="schedule" className="schedule-strip"><div className="section-lead"><div><p className="eyebrow blue">Next up</p><h2>Friday nights start here.</h2></div><a href="#full-schedule">Full schedule <span aria-hidden="true">→</span></a></div><div className="game-row">{games.slice(0,3).map((game,index)=><article className={index===0?'game featured':'game'} key={game.opponent}><div className="game-date">{game.date}</div><img src={`/assets/opponents/${game.logo}`} alt=""/><div><p>{game.opponent}</p><span>{game.detail}</span></div><div className="game-place"><span aria-hidden="true">◆</span>{game.place}</div></article>)}</div></section>

    <section id="program" className="program-grid"><div className="program-photo"><img src="/assets/action.jpg" alt="Edmond North player carrying the ball into the end zone"/><div className="photo-stamp">North<br/>Football</div></div><div className="program-copy"><p className="eyebrow">The program</p><h2>More than four quarters.</h2><p>Edmond North Football develops disciplined teammates, confident leaders, and young men prepared to succeed beyond game night.</p><div className="program-links"><a id="team" href="#coaches"><b aria-hidden="true">01</b><span><strong>Meet the Huskies</strong><small>Varsity, JV, freshman & staff</small></span><b aria-hidden="true">›</b></a><a id="parents" href="#contact"><b aria-hidden="true">02</b><span><strong>Parent hub</strong><small>Dates, forms, camps & communication</small></span><b aria-hidden="true">›</b></a><a href="/recruiting/"><b aria-hidden="true">03</b><span><strong>Recruiting center</strong><small>Player profiles & coach contact</small></span><b aria-hidden="true">›</b></a><a href="#tradition"><b aria-hidden="true">04</b><span><strong>Tradition</strong><small>Alumni, records & program history</small></span><b aria-hidden="true">›</b></a></div></div></section>
    <section id="recruiting" className="recruiting"><div className="recruiting-intro"><div><p className="eyebrow blue">Recruiting</p><h2>Put the next level on notice.</h2><p>Recruiting profiles are being updated. These player cards and Hudl links are placeholders until the staff adds verified information.</p></div><a className="button dark" href="mailto:huskies@edmondnorthfb.com?subject=Edmond%20North%20Football%20Recruiting">Contact the program <span aria-hidden="true">→</span></a></div><div className="recruiting-grid">{recruits.map(([number,name,position,year,image])=><article className="player-card" key={number}><div className="player-photo"><img src={`/assets/players/${image}`} alt={`${name}, Edmond North football ${position}`}/><span className="player-number">{number}</span></div><div className="player-info"><div><p className="player-position">{position}</p><h3>{name}</h3><span>{year} · 6A-I Varsity</span></div><a className="hudl-link" href="https://www.hudl.com" target="_blank" rel="noreferrer">Mock Hudl link ↗</a></div></article>)}</div></section>

    <section id="full-schedule" className="full-schedule"><div className="schedule-heading"><p className="eyebrow">2026 Varsity</p><h2>The road ahead.</h2><div className="schedule-tabs" aria-label="Schedule level"><span className="active">Varsity</span><span>JV</span><span>Freshman</span></div></div><div className="schedule-list">{games.map((game,index)=><article key={game.opponent}><span className="game-number">{String(index+1).padStart(2,'0')}</span><time>{game.date}</time><img src={`/assets/opponents/${game.logo}`} alt=""/><div><strong>{game.opponent}</strong><small>{game.detail}</small></div><span className={`location ${game.place.toLowerCase()}`}>{game.place}</span><a href="https://maps.app.goo.gl/dDnq1iz2Q7UYVCaL8" target="_blank" rel="noreferrer" aria-label={`Game details for ${game.opponent}`}>→</a></article>)}</div><p className="schedule-note">Dates and times reflect the current program calendar and may change. Follow Edmond North Football for game-week updates.</p></section>

    <section id="media" className="media-feature"><img src="/assets/game-night.jpg" alt="Edmond North offense during a night game"/><div className="media-overlay"/><div className="media-copy"><p className="eyebrow">Game day</p><h2>Can&apos;t make the stands?</h2><p>Follow every Friday night with live KREF coverage and program updates from the sideline.</p><div><a className="button light" href="https://www.goenhsathletics.com/KREF-Streaming" target="_blank" rel="noreferrer"><span aria-hidden="true">●</span> Listen live</a><a className="button outline" href="https://www.instagram.com/edmondnorthfb/" target="_blank" rel="noreferrer"><span aria-hidden="true">◎</span> Follow the Huskies</a></div></div></section>

    <section id="coaches" className="coaches"><div className="section-lead"><div><p className="eyebrow blue">Leadership</p><h2>Meet the staff.</h2></div><a href="mailto:huskies@edmondnorthfb.com?subject=Coaching%20Staff">Contact the program <span aria-hidden="true">→</span></a></div><div className="coach-grid">{coaches.map(([name,role],i)=><article key={name}><span>0{i+1}</span><div><h3>{name}</h3><p>{role}</p></div></article>)}</div></section>

    <section id="support" className="support"><div className="support-copy"><p className="eyebrow">Back the pack</p><h2>Put your name<br/>behind the North.</h2><p>Sled Team membership and local sponsorships directly support every level of Edmond North Football—from equipment and meals to camps and team experiences.</p><div><a className="button light" href="https://pci.jotform.com/form/260876506724161" target="_blank" rel="noreferrer">Join the Sled Team <span aria-hidden="true">→</span></a><a className="button outline" href="https://pci.jotform.com/form/260876506724161" target="_blank" rel="noreferrer">Become a sponsor</a></div></div><div className="support-mark"><img src="/assets/badge.png" alt="Edmond North Huskies badge"/><span>Every player.<br/>Every level.<br/>One program.</span></div></section>

    <section id="tradition" className="tradition"><p className="eyebrow blue">The standard</p><blockquote>“Building champions on and off the field.”</blockquote><div><span><strong>Varsity</strong>Friday nights</span><span><strong>JV</strong>Next men up</span><span><strong>Freshman</strong>The foundation</span></div></section>

    <footer id="contact"><div className="footer-brand"><img src="/assets/wordmark.png" alt="Edmond North Football"/><p>1001 W. Danforth Rd<br/>Edmond, OK 73003</p></div><div><h3>Program</h3><a href="#schedule">Schedule</a><a href="#team">Team</a><a href="#coaches">Coaches</a><a href="#recruiting">Recruiting</a></div><div><h3>Get involved</h3><a href="#support">Sled Team</a><a href="#support">Sponsors</a><a href="#media">Media</a><a href="mailto:huskies@edmondnorthfb.com">Contact</a></div><div className="footer-contact"><h3>Stay connected</h3><a href="mailto:huskies@edmondnorthfb.com">huskies@edmondnorthfb.com</a><a href="tel:4053402875">(405) 340-2875</a><a href="https://www.instagram.com/edmondnorthfb/" target="_blank" rel="noreferrer">Instagram</a></div><p className="copyright">© 2026 Edmond North Football · Home of the Huskies</p></footer>
  </main>;
}
