import {animate,hover,inView,stagger} from 'motion';

if(!matchMedia('(prefers-reduced-motion: reduce)').matches){
  document.documentElement.classList.add('motion-ready');
  const hero=[...document.querySelectorAll<HTMLElement>('.hero .hero-line,.hero .hero-location,.hero .hero-actions,.hero .hero-stat')];
  if(hero.length){hero.forEach(el=>{el.style.opacity='0';el.style.transform='translateY(26px)'});animate(hero,{opacity:1,transform:'translateY(0px)'},{duration:1.3,delay:stagger(.13),ease:[.22,1,.36,1]})}
  const reveal=(selector:string,children:string,amount=.12,duration=.48,step=.055)=>document.querySelectorAll<HTMLElement>(selector).forEach(section=>inView(section,()=>{const items=[...section.querySelectorAll<HTMLElement>(children)];items.forEach(el=>{el.style.opacity='0';el.style.transform='translateY(18px)'});animate(items,{opacity:1,transform:'translateY(0px)'},{duration,delay:stagger(step),ease:[.22,1,.36,1]})},{amount}));
  reveal('.standalone-schedule','.schedule-list article',.08);reveal('.recruiting-standalone','.player-profile',.04);reveal('.tradition','.eyebrow,blockquote,.roster-cta,.program-levels article',.12,.9,.1);reveal('.weekly-board','.leader-grid article');
  document.querySelectorAll<HTMLElement>('.upcoming-logo-crop').forEach(mark=>inView(mark,()=>{animate(mark,{opacity:[.35,1],transform:['translateX(-10px)','translateX(0px)']},{duration:.75,ease:[.22,1,.36,1]})},{amount:.5}));
  document.querySelectorAll<HTMLElement>('.standalone-schedule .schedule-list article').forEach(card=>{const logo=card.querySelector<HTMLElement>('.opponent-mark img');if(logo)hover(card,()=>{animate(logo,{translateX:'-47%'},{duration:.22});return()=>{animate(logo,{translateX:'-50%'},{duration:.22})}})});
  document.querySelectorAll<HTMLElement>('.kickoff-countdown b[data-unit]').forEach(digit=>{let prior=digit.textContent;new MutationObserver(()=>{if(prior===digit.textContent)return;prior=digit.textContent;animate(digit,{opacity:[.25,1],transform:['translateY(-7px)','translateY(0px)']},{duration:.25,ease:'easeOut'})}).observe(digit,{childList:true,subtree:true})});
  document.querySelectorAll<HTMLDetailsElement>('.player-profile').forEach(card=>card.addEventListener('toggle',()=>{const detail=card.querySelector<HTMLElement>('.profile-detail');if(card.open&&detail)animate(detail,{opacity:[0,1],transform:['translateY(-10px)','translateY(0px)']},{duration:.32,ease:[.22,1,.36,1]})}));
  document.querySelectorAll<HTMLElement>('.leader-grid article>b').forEach(value=>{const target=Number((value.childNodes[0]?.textContent||'').trim().replace(/,/g,''));if(Number.isFinite(target))inView(value,()=>{animate(0,target,{duration:1.05,ease:[.22,1,.36,1],onUpdate:n=>{if(value.childNodes[0])value.childNodes[0].textContent=`${Math.round(n).toLocaleString()} `}})},{amount:1})});
  const roster=document.querySelector('.roster-list');if(roster){const tabs=[...roster.querySelectorAll<HTMLButtonElement>('.roster-tabs button')];const active=document.createElement('span');active.className='roster-tab-active';{const selected=tabs.find(tab=>tab.getAttribute('aria-selected')==='true');if(selected)selected.insertBefore(active,selected.firstChild)};tabs.forEach(tab=>tab.addEventListener('click',()=>{tab.insertBefore(active,tab.firstChild);animate(active,{opacity:[.45,1],transform:['scaleX(.75)','scaleX(1)']},{duration:.3,ease:[.22,1,.36,1]})}));const observer=new MutationObserver(()=>{const visible=[...roster.querySelectorAll<HTMLElement>('article')].filter(el=>!el.hidden);visible.forEach((el,i)=>animate(el,{opacity:[0,1],transform:['translateY(8px)','translateY(0px)']},{duration:.22,delay:Math.min(i*.012,.18)}))});observer.observe(roster,{attributes:true,subtree:true,attributeFilter:['hidden']})}
  const track=document.querySelector<HTMLElement>('.photo-recap-track');if(track&&innerWidth<=600){let start=0,origin=0,current=0;const minX=Math.min(0,(track.parentElement?.clientWidth||0)-track.scrollWidth);track.addEventListener('pointerdown',event=>{start=event.clientX;origin=current;track.setPointerCapture(event.pointerId)});track.addEventListener('pointermove',event=>{if(!track.hasPointerCapture(event.pointerId))return;current=Math.max(minX,Math.min(0,origin+event.clientX-start));track.style.transform=`translateX(${current}px)`});track.addEventListener('pointerup',event=>{track.releasePointerCapture(event.pointerId);const snapped=Math.max(minX,Math.min(0,Math.round(current/(innerWidth*.82))*innerWidth*.82));animate(track,{transform:`translateX(${snapped}px)`},{type:'spring',stiffness:320,damping:28});current=snapped})}
}
